plugins:
  - rubocop-rails
  - rubocop-rspec

require:
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']
  Exclude:
    - 'spec/factories/**/*'

Layout/LineLength:
  Max: 120

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: false

Rails/RedundantForeignKey:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
