services:
  app:
    tty: true
    stdin_open: true
    container_name: vertical_logistics
    entrypoint: "./entrypoint.sh"
    env_file: .env
    build:
      context: .
      target: dev
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    ports:
      - 3000:3000
    command: bash -c "rails s -p '3000' -b '0.0.0.0'"

volumes:
  rubygems:
